#language: cpp
language: objective-c

matrix:
    include:
        - os: osx
          compiler: clang

# enabling multi platform build (under travis beta)
# requires emailing support@travis-ci.com for this to be enabled for our repo
# http://docs.travis-ci.com/user/multi-os/
# For now cheat to set language to objective-c
#os:
#    - linux
#    - osx

before_install:
    - source ./travis/before_install.sh

install: ulimit -c

before_script: 
    # Set the core file limit to unlimited so a core file is generated upon crash
    - ulimit -c unlimited -S

# build test project
script: 
    - source ./travis/script.sh

# Change this to your needs
    # script: ./configure && make
