language: cpp

matrix:
    include:
        - os: osx
          env: PLATFORM=osx
          compiler: clang
        - os: osx
          env: PLATFORM=ios
          compiler: clang
        - os: linux
          env: PLATFORM=android
          compiler: gcc
          addons:
            apt:
              packages: [ 'openjdk-7-jdk', 'lib32z1-dev', 'lib32stdc++6' ]
        - os: linux
          env: PLATFORM=linux
          compiler: gcc
          addons:
            apt:
              sources: [ 'kalakris-cmake', 'ubuntu-toolchain-r-test' ]
              packages: [ 'cmake', 'gcc-4.8', 'g++-4.8', 'xorg-dev', 'libglu1-mesa-dev' ]

before_install:
    - git submodule init && git submodule update
    - source ./travis/before_install.sh

install: ulimit -c

before_script:
    # Set the core file limit to unlimited so a core file is generated upon crash
    - ulimit -c unlimited -S

# build test project
script:
    - source ./travis/script_build_tests.sh
    - source ./travis/script_run_tests.sh
    - source ./travis/script_build.sh

after_success:
    - source ./travis/script_deploy_android_snapshot.sh

sudo: false
