cameras:
    camera1:
        type: perspective
        focal_length: [[16, 2], [20, 6]] # pairs of [zoom, focal len]
        vanishing_point: [-250, -250] # relative to center of screen, in pixels

lights:
    light1:
        type: directional
        origin: world
        direction: [1, 1, -1]
        diffuse: [.7, .7, .7, 1.]
        ambient: [.3, .3, .3, 1.]

sources:
    osm:
        type: MVT
        url:  http://vector.mapzen.com/osm/all/{z}/{x}/{y}.mvt

layers:
    earth:
        data: { source: osm }
        draw:
            polygons:
                order: 0
                color: '#f0ebeb'

    landuse:
        data: { source: osm }
        filter:
            name: true
            any:
                - { $zoom: { min: 9 }, area: { min: 10000000 } }
                - { $zoom: { min: 10 }, area: { min: 3300000 } }
                - { $zoom: { min: 12 }, area: { min: 1000000 } }
                - { $zoom: { min: 13 }, area: { min: 10000 } }
                - { $zoom: { min: 15 } }
        draw:
            polygons:
                order: 1
                interactive: true
        green:
            filter: { kind: [park, graveyard, cemetery, forest, recreation_ground] }
            draw:
                polygons:
                    order: 2
                    color: '#bddec5'
        blue:
            filter: { kind: [commercial, industrial] }
            draw:
                polygons:
                    color: '#C0CDCD'
        orange:
            filter: { kind: [university] }
            draw:
                polygons:
                    color: '#D9CFC3'

    water:
        data: { source: osm }
        filter:
            any:
                # show smaller water areas at higher zooms
                - { $zoom: { min: 0 }, area: { min: 10000000 } }
                - { $zoom: { min: 10 }, area: { min: 1000000 } }
                - { $zoom: { min: 12 }, area: { min: 100000 } }
                - { $zoom: { min: 15 }, area: { min: 1000 } }
                - { $zoom: { min: 18 } }
        draw:
            polygons:
                order: 2
                color: '#9dc3de'

    roads:
        data: { source: osm }
        filter:
            not: {kind: [rail]}
        draw:
            lines:
                order: 4
                width: .02
                cap: round
                color: white
                outline:
                    width: .01
                    cap: round
                    color: '#999'
        rounded:
            filter: { $zoom: { min: 18 } }
            draw:
                lines:
                    cap: round
        highway:
            filter: { kind: highway }
            draw:
                lines:
                    color: '#D16768'
                    width: .04
            link:
                filter: { is_link: yes }
                draw:
                    lines:
                        color: '#aaa'
                        width: .001
        path:
            filter:
                kind: path
            draw:
                lines:
                    color: '#bbb'
                    width: .001
        airports:
            filter: { aeroway: true }
            draw:
                lines:
                    color: '#ddd'
                    outline:
                        width: 0
            taxiways:
                filter: { aeroway: taxiway }
                draw:
                    lines:
                        width: .005
            runways:
                filter: { aeroway: runway }
                draw:
                    lines:
                        color: '#FFE4B5'
                        width: .02
                        cap: square
                        outline:
                            color: orange
                            width: 0.01
    buildings:
        data: { source: osm }
        filter: { $zoom: { min: 14 } }
        draw:
            polygons:
                order: 50
                color: [.65, .65, .65]
        # turn interactive feature selection on for buildings with names
        interactive:
            filter: { name: true }
            draw: { polygons: { interactive: true } }
        extruded:
            filter: { $zoom: { min: 15 } }
            draw:
                polygon:
                    extrude: true
        high-line:
            filter: {roof_material: grass}
            draw:
                polygon:
                    color: '#bddec5'

